# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Virtual_machines_shared\tass\Project2\projects\mainwindow.ui',
# licensing of 'Z:\Virtual_machines_shared\tass\Project2\projects\mainwindow.ui' applies.
#
# Created: Sun Jan 13 15:42:05 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

import find_routes as fr
import airport_data as apd
import airlines_data as ald

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 490)
        MainWindow.setMinimumSize(QtCore.QSize(550, 490))
        MainWindow.setMaximumSize(QtCore.QSize(550, 490))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 511, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.weightsTabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.weightsTabWidget.setObjectName("weightsTabWidget")
        self.airports_tab = QtWidgets.QWidget()
        self.airports_tab.setObjectName("airports_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.airports_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 290))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.airports_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.airports_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.airports_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.airports_layout.setContentsMargins(-1, 0, -1, -1)
        self.airports_layout.setObjectName("airports_layout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.airports_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.airports_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.airports_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.airports_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.airports_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.airports_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.airports_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.airports_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.airports_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.airports_layout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.airports_layout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.airports_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.airports_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.airports_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.airports_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.airports_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.airports_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.comboBox_9 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.airports_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.comboBox_10 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.airports_layout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.comboBox_11 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_11.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.airports_layout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.airports_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.airports_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.weightsTabWidget.addTab(self.airports_tab, "")
        self.airlines_tab = QtWidgets.QWidget()
        self.airlines_tab.setObjectName("airlines_tab")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.airlines_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 241, 291))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.airlines_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.airlines_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.airlines_layout.setContentsMargins(0, 0, 0, 0)
        self.airlines_layout.setObjectName("airlines_layout")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.airlines_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_12 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.airlines_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.airlines_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_13 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.airlines_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.airlines_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBox_14 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.airlines_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.airlines_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_15 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.airlines_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.airlines_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.comboBox_16 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.airlines_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.airlines_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.comboBox_17 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.airlines_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_17)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.airlines_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.comboBox_18 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.airlines_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_18)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.airlines_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.comboBox_19 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.airlines_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_19)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.airlines_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.comboBox_20 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.airlines_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_20)
        self.weightsTabWidget.addTab(self.airlines_tab, "")
        self.verticalLayout.addWidget(self.weightsTabWidget)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout.addWidget(self.searchButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.weightsTabWidget.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(0)
        self.comboBox_8.setCurrentIndex(0)
        self.comboBox_9.setCurrentIndex(0)
        self.comboBox_10.setCurrentIndex(0)
        self.comboBox_11.setCurrentIndex(5)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_12.setCurrentIndex(0)
        self.comboBox_13.setCurrentIndex(0)
        self.comboBox_14.setCurrentIndex(0)
        self.comboBox_15.setCurrentIndex(0)
        self.comboBox_16.setCurrentIndex(0)
        self.comboBox_17.setCurrentIndex(0)
        self.comboBox_18.setCurrentIndex(0)
        self.comboBox_19.setCurrentIndex(0)
        self.comboBox_20.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def searchButtonClicked(self):
        airport_weights_dic = dict(zip(list(apd.airport_rated)[3:14], [self.comboBox.currentIndex(), self.comboBox_2.currentIndex(), self.comboBox_3.currentIndex(), self.comboBox_4.currentIndex(), self.comboBox_5.currentIndex(), self.comboBox_6.currentIndex(), self.comboBox_7.currentIndex(), self.comboBox_8.currentIndex(), self.comboBox_9.currentIndex(), self.comboBox_10.currentIndex(), self.comboBox_11.currentIndex() - 5]))
        airlines_weights_dic = dict(zip(list(ald.airlines_rated)[3:12], [self.comboBox_12.currentIndex(), self.comboBox_13.currentIndex(), self.comboBox_14.currentIndex(), self.comboBox_15.currentIndex(), self.comboBox_16.currentIndex(), self.comboBox_17.currentIndex(), self.comboBox_18.currentIndex(), self.comboBox_19.currentIndex(), self.comboBox_20.currentIndex()]))
        source = self.lineEdit.text()
        dest = self.lineEdit_2.text()
        results = fr.get_sorted_paths(source, dest, airport_weights_dic, airlines_weights_dic)
        result_string = ''
        result_string = '\n'.join(map(str, results))
        self.textEdit.setText(result_string)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Search for flight", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Source city", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Destination city", None, -1))
        self.lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Source city name", None, -1))
        self.lineEdit_2.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Destination city name", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Overall", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Queuing", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Terminal cleanliness", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Terminal seating", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Terminal signs", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Food beverages", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Airport shopping", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "WiFi connectivity", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Airport staff", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Recommended", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Passengers traffic", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_3.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_3.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_3.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_4.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_4.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_4.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_4.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_4.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_4.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_5.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_5.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_5.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_5.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_5.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_5.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_6.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_6.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_6.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_6.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_6.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_6.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_7.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_7.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_7.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_7.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_7.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_7.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_8.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_8.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_8.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_8.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_8.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_8.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_9.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_9.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_9.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_9.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_9.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_9.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_10.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_10.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_10.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_10.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_10.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_10.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_11.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "-5", None, -1))
        self.comboBox_11.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "-4", None, -1))
        self.comboBox_11.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "-3", None, -1))
        self.comboBox_11.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "-2", None, -1))
        self.comboBox_11.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.comboBox_11.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_11.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_11.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_11.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_11.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_11.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.weightsTabWidget.setTabText(self.weightsTabWidget.indexOf(self.airports_tab), QtWidgets.QApplication.translate("MainWindow", "Airports", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Overall", None, -1))
        self.comboBox_12.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_12.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_12.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_12.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_12.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_12.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Seat comfort", None, -1))
        self.comboBox_13.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_13.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_13.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_13.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_13.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_13.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Cabin staff", None, -1))
        self.comboBox_14.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_14.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_14.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_14.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_14.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_14.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Food beverages", None, -1))
        self.comboBox_15.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_15.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_15.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_15.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_15.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_15.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Inflight entertainment", None, -1))
        self.comboBox_16.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_16.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_16.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_16.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_16.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_16.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Ground service", None, -1))
        self.comboBox_17.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_17.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_17.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_17.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_17.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_17.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "WiFi connectivity", None, -1))
        self.comboBox_18.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_18.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_18.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_18.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_18.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_18.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Value for money", None, -1))
        self.comboBox_19.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_19.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_19.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_19.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_19.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_19.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Recommended", None, -1))
        self.comboBox_20.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Does not matter", None, -1))
        self.comboBox_20.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_20.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_20.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_20.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_20.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.weightsTabWidget.setTabText(self.weightsTabWidget.indexOf(self.airlines_tab), QtWidgets.QApplication.translate("MainWindow", "Airlines", None, -1))
        self.searchButton.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Results:", None, -1))
        QtCore.QObject.connect(self.searchButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.searchButtonClicked)
